### PR TITLE
React based example on lib rlds

### PR DESCRIPTION
**Pull request by ButuzGOL**
React based example on lib rlds

https://github.com/mashmatrix/react-lightning-design-system/issues/118

### CODE REVIEW

**Comment by ButuzGOL** [comment]
Any feedback on pull request ?

**Comment by kaelig** [comment]
Thank you so much for your help @ButuzGOL!

I had a look locally and it's a great addition to the project.

As the amount of JS code is getting larger, maybe a next step would be to add eslint to the react branch. What are your thoughts? I'm fine with whatever code style, as I won't be the one working on this branch.

**Comment by kaelig** [comment]
FYI @owenschoppe

**Comment by ButuzGOL** [comment]
yes sure

**Pull request merged**
